name: 'Auth0 Actions-As-Code'
description: 'Deploy Auth0 actions'
author: 'Stefanos Chrs'
branding:
  color: 'orange'
  icon: 'star'
inputs:
  auth0_client_id:
    required: true
    description: 'Auth0 Client ID'
  auth0_client_secret:
    required: true
    description: 'Auth0 Client Secret'
  auth0_tenant_domain:
    required: true
    description: 'Auth0 Tenant Domain'
  config_path:
    required: false
    description: 'Path to the config file'
    default: 'config.yml'
  actions_runtime:
    required: false
    description: 'Runtime version of your action'
    default: 'node22'
runs:
  using: 'docker'
  image: 'Dockerfile'
